spring:
  application:
    name: example-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    url: jdbc:postgresql://localhost/example-databse
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false

example.topic-name: example.topic
